### ISSUE TITLE
Better menu formatting

### ISSUE THREAD

**Issue by vinniejames** [vinniejames/coinfox#27]
Cleanup layout
Add "?" link to repo

**Comment by williamluke4** [comment]
@vinniejames  Hey Vinnie, check out my fork. I'v upgraded to es6, added styled-components and iv also made some changes to the AddCoin component. One issue currently is that the dev server taking to long to recompile

**Comment by vinniejames** [comment]
Looking good man! I'll take a closer look this week

**Comment by vinniejames** [comment]
Can we add a language selection drop-down: English, French, German. Then save that in local storage.pref, making sure to display the correct language?

**Comment by williamluke4** [comment]
Done

**Comment by williamluke4** [comment]
@vinniejames The translation string should be passed down as a prop from the App.js to avoid having to call translationStrings on every component that requires it!

**Comment by vinniejames** [comment]
Yes, that makes sense. Good catch!

>

**Comment by vinniejames** [comment]
Great work @williamluke4 !! Some feedback on the fork:

1. Adding existing/additional coins no longer works. If I add Bitcoin, eg 1 BTC avg cost $100. Then add another 1 BTC avg cost $200. My holding should update to 2 BTC with average cost basis of $150 ($300 total). Instead there is a console error `index.js:133 Uncaught TypeError: this._addExistingCoin is not a function`

2. Window onload console error `index.js:1 Uncaught TypeError: Assignment to constant variable at window.addEventListener (index.js:1)`

3. Trying to keep console.logs minimal, can we remove the log for `{rows: Array(1392)}`?

4. The menu formatting is looking good, a couple suggestions:

- The dropdown picker is a bit slow, since its doing a network request on nearly every keystroke. Instead can we fetch it once from the API, then use `array.filter` on each keystroke?
- "Language preference" looks to be hardcoded, can we Google translate it and drop it into the i18n json?
- Lets use the `ticker` instead of the `name` for the suggestions list? Currently if you search for `BTC` as suggested by the placeholder nothing comes up, you have to instead search for `Bitcoin`
- The bubble showing the current preference feels a bit redundant, since the dropdown already shows the current selection, can we remove it?
- To keep things consistent can we loose the text zoom on :hover for the "Go"button and use "Add Coin" instead?

Want to get these items fixed up then submit a PR? I'll try to make some time to write tests to avoid any regressions

**Comment by williamluke4** [comment]
- [x] Adding existing/additional coins no longer works. If I add Bitcoin, eg 1 BTC avg cost $100. Then add another 1 BTC avg cost $200. My holding should update to 2 BTC with average cost basis of $150 ($300 total). Instead there is a console error index.js:133 Uncaught TypeError: this._addExistingCoin is not a function

- [ ] Window onload console error index.js:1 Uncaught TypeError: Assignment to constant variable at window.addEventListener (index.js:1)
  * __Will have to sort this out at a later date__

- [x] Trying to keep console.logs minimal, can we remove the log for {rows: Array(1392)}?

- [ ] The dropdown picker is a bit slow, since its doing a network request on nearly every keystroke. Instead can we fetch it once from the API, then use array.filter on each keystroke (maybe debounce as well)?
  * __When I have time will change it over, seems pretty responsive to me but am yet to try it on mobile__
- [ ] "Language preference" looks to be hardcoded, can we Google translate it and drop it into the i18n json?
  * __No idea how this would be done__
- [x] Lets use the ticker instead of the name for the suggestions list? Currently if you search for BTC as suggested by the placeholder nothing comes up, you have to instead search for Bitcoin

- [x] The bubble showing the current preference feels a bit redundant, since the dropdown already shows the current selection, can we remove it?

- [x] To keep things consistent can we loose the text zoom on :hover for the "Go"button and use "Add Coin" instead?

**Comment by vinniejames** [comment]
Nice work! I can up the translation string

The drop-down picker is pretty slow on mobile networks, the app is slowly transitioning to mobile only with the pending iOS/Android mobile app release. So I'd definitely like to see this adjusted, per my comment, before merging.

Hesitant to merge with a console error, from the log it sounds like a relatively simple fix, are you trying to reassign a 'const' variable someplace?

**Comment by vinniejames** [comment]
Want to open a PR? I'll have time to review this weekend

**Comment by vinniejames** [comment]
https://github.com/vinniejames/coinfox/pull/47
